name: faminity
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: #ffffff
  adaptive_icon_padding: true

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/icons/
fonts:
    - family: TT Commons
      fonts:
        - asset: assets/fonts/TT Commons Regular.otf
        - asset: assets/fonts/TT Commons Bold.otf
        - asset: assets/fonts/TT Commons Medium.otf
        - asset: assets/fonts/TT Commons Light.otf

